name: Build

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

env:
  USERNAME: JonatanNevo
  FEED_URL: https://nuget.pkg.github.com/JonatanNevo/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/JonatanNevo/index.json,readwrite"

jobs:
  build_windows:
    name: Build Windows ${{ matrix.c_compiler }}
    runs-on: windows-latest
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      matrix:
        c_compiler: [ clang, cl ]
        include:
          - c_compiler: cl
            cpp_compiler: cl
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@b3dd708d38df5c856fe1c18dc0d59ab771f93921
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_ROOT }}/vcpkg.exe fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          .$(${{ env.VCPKG_ROOT }}/vcpkg.exe fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}', '-DCMAKE_C_COMPILER=${{ matrix.c_compiler }}']"
          buildPreset: 'dist'
          testPreset: 'test-release'

  build_macos:
    name: Build MacOS
    runs-on: macos-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: lukka/get-cmake@latest

      - name: Install Brew Dependencies
        uses: gerlero/brew-install@v1.1.2
        with:
          packages: mono

      # run-vcpkg is setting `VCPKG_FORCE_SYSTEM_BINARIES` env var and there is not way to unset it, so we have to bootstrap vcpkg manually.
      - name: Bootstrap vcpkg
        shell: bash
        run: |
          ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.sh

      - name: Add NuGet sources
        shell: bash
        run: |
          echo "Fetching nuget..."
          NUGET_PATH=$(${{ env.VCPKG_ROOT }}/vcpkg fetch nuget | tail -n 1)
          
          mono "$NUGET_PATH" sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}" || true
          
          mono "$NUGET_PATH" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"

      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_COMPILER=clang++', '-DCMAKE_C_COMPILER=clang']"
          buildPreset: 'dist'
          testPreset: 'test-release'

  build_linux:
    name: Build Linux ${{ matrix.os_name }} ${{ matrix.c_compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        c_compiler: [ clang, gcc ]
        include:
          - os: ubuntu-latest
            os_name: Ubuntu
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            os_name: Ubuntu
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: lukka/get-cmake@latest

      - name: Install Clang
        if: matrix.c_compiler == 'clang'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100
          sudo update-alternatives --set clang /usr/bin/clang-20
          sudo update-alternatives --set clang++ /usr/bin/clang++-20
          clang --version
          clang++ --version

      - run: pip install portal_tool
      - run: python -m portal_tool install -y --only-dependencies

      - uses: lukka/run-vcpkg@b3dd708d38df5c856fe1c18dc0d59ab771f93921
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Install deps
        shell: bash
        run: sudo apt-get install -y mono-complete libx11-dev xorg-dev libglu1-mesa-dev libltdl-dev

      - name: Add NuGet sources
        shell: bash
        run: |
          echo "Fetching nuget..."
          NUGET_PATH=$(${{ env.VCPKG_ROOT }}/vcpkg fetch nuget | tail -n 1)
          
          mono "$NUGET_PATH" sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}" || true
          
          mono "$NUGET_PATH" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"

      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_COMPILER=clang++', '-DCMAKE_C_COMPILER=clang']"
          buildPreset: 'dist'
          testPreset: 'test-release'